=== uo277516/SEW2023/xml/rutas.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.uniovi.es" xmlns="https://www.uniovi.es">
  <xs:element name="rutas">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="ruta" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ruta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="tipo" />
        <xs:element ref="medio" />
        <xs:element minOccurs="0" maxOccurs="1" ref="fecha_inicio" />
        <xs:element minOccurs="0" maxOccurs="1" ref="hora_inicio" />
        <xs:element ref="duracion" />
        <xs:element ref="agencia" />
        <xs:element ref="descripcion" />
        <xs:element ref="personas_adecuadas" />
        <xs:element ref="inicio" />
        <xs:element ref="referencias" />
        <xs:element ref="recomendacion" />
        <xs:element ref="hitos" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="xs:string" />
  <xs:element name="tipo" type="xs:string" />
  <xs:element name="medio" type="xs:string" />
  <xs:element name="fecha_inicio" type="xs:date" />
  <xs:element name="hora_inicio" type="xs:time" />
  <xs:element name="duracion" type="xs:duration" />
  <xs:element name="agencia" type="xs:string" />
  <xs:element name="descripcion" type="xs:string" />
  <xs:element name="personas_adecuadas" type="xs:string" />
  <xs:element name="inicio">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lugar" />
        <xs:element ref="direccion" />
        <xs:element ref="coordenadas" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="lugar" type="xs:string" />
  <xs:element name="direccion" type="xs:string" />
  <xs:element name="coordenadas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitud" />
        <xs:element ref="latitud" />
        <xs:element ref="altitud" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitud" type="xs:float" />
  <xs:element name="latitud" type="xs:float" />
  <xs:element name="altitud" type="xs:float" />
  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="titulo" />
        <xs:element ref="bibliografia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titulo" type="xs:string" />
  <xs:element name="bibliografia" type="xs:string" />
  <xs:element name="recomendacion">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0" />
        <xs:maxInclusive value="10" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="hitos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="hito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="descripcion" />
        <xs:element ref="coordenadas" />
        <xs:element ref="distancia" />
        <xs:element ref="galeria_fotos" />
        <xs:element minOccurs="0" maxOccurs="1" ref="galeria_videos" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="distancia">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:float">
          <xs:attribute name="unidades" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="galeria_fotos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="5" ref="foto" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto" type="xs:string" />
  <xs:element name="galeria_videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="3" ref="video" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="video" type="xs:string" />
</xs:schema>

=== uo277516/SEW2023/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas
xmlns="https://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.uniovi.es rutas.xsd">

  <!-- PRIMERA RUTA -->
    <ruta>
        <nombre>Koh Rong Sanloem playas</nombre>
        <tipo>Senderismo</tipo>
        <medio>A pie</medio>
        <fecha_inicio>2014-11-22</fecha_inicio>
        <hora_inicio>09:00:00</hora_inicio>
        <duracion>P2DT6H20M</duracion>
        <agencia>Wikiloc</agencia>
        <descripcion>Recorre los principales faros son sus espectaculares vistas y las playas de Cambodia.</descripcion>
        <personas_adecuadas>Personas en buena forma física</personas_adecuadas>
        <inicio>
            <lugar>Koh Rong Samloem</lugar>
            <direccion>Koh Rong Samloem, Preah Sihanouk 18205, Camboya</direccion>
            <coordenadas>
              <longitud>10.5816667</longitud>
              <latitud>103.30555555555556</latitud>
              <altitud>13</altitud>
            </coordenadas>
        </inicio>
        <referencias>
          <referencia>
            <titulo>¿Qué hacer en Koh Rong Samloem?</titulo>
            <bibliografia>https://mochilerosentailandia.com/2016/05/que-hacer-en-koh-rong-samloem/</bibliografia>
          </referencia>
          <referencia>
            <titulo>Ruta en Wikiloc</titulo>
            <bibliografia>https://es.wikiloc.com/rutas-senderismo/koh-rong-sanloem-playas-cambodia-camboya-8309043</bibliografia>
          </referencia>
          <referencia>
            <titulo>10 Cosas Qué Hacer Sunset Beach En Koh Rong</titulo>
            <bibliografia>https://elmundoporrecorrer.com/sunset-beach-koh-rong-sanloem/</bibliografia>
          </referencia>
        </referencias>
        <recomendacion>8</recomendacion>
        <hitos>
          <!--Primer hito-->
          <hito>
            <nombre>Saracen Beach</nombre>
            <descripcion>Popular playa turística de Koh Rong Samloem. Esta playa es impresionante. Está bastante ocupado con resorts y restaurantes que bordean la playa, pero no hay ciudad.</descripcion>
            <coordenadas>
              <longitud>10.572066273717155</longitud>
              <latitud>103.32257500556706</latitud>
              <altitud>8</altitud>
            </coordenadas>
            <distancia unidades="km">15.5</distancia>
            <galeria_fotos>
              <foto>SaracenBeachjpg.jpg</foto>
            </galeria_fotos>
          </hito>
          <!--Segundo hito-->
          <hito>
            <nombre>Onederz Koh Rong Sanloem</nombre>
            <descripcion>Bungalows en primera línea de playa, en los que puedes descansar entre días.</descripcion>
            <coordenadas>
              <longitud>10.577285867332305</longitud>
              <latitud>103.31051034974506</latitud>
              <altitud>5</altitud>
            </coordenadas>
            <distancia unidades="km">6.7</distancia>
            <galeria_fotos>
              <foto>OrchidBungalows.jpg</foto>
            </galeria_fotos>
          </hito>
          <!--Tercer hito-->
          <hito>
            <nombre>Sunset Beach</nombre>
            <descripcion>Playa semidesierta muy bonita, pero con acceso complicado. Atardeceres espectaculares.</descripcion>
            <coordenadas>
              <longitud>10.576130272598032</longitud>
              <latitud>103.29592152142439</latitud>
              <altitud>14</altitud>
            </coordenadas>
            <distancia unidades="km">2.3</distancia>
            <galeria_fotos>
              <foto>SunsetBeach.jpg</foto>
            </galeria_fotos>
          </hito>
        </hitos>
    </ruta>

    <!-- SEGUNDA RUTA -->
    <ruta>
      <nombre>Templo Angkor Wat Recorrido circular desde Riem Siep</nombre>
      <tipo>Monumentos/Ciudad</tipo>
      <medio>Mountain Bike</medio>
      <fecha_inicio>2017-05-01</fecha_inicio>
      <hora_inicio>07:00:00</hora_inicio>
      <duracion>PT2H25M</duracion>
      <agencia>Wikiloc</agencia>
      <descripcion>Paseo en bici moderado. Se necesita buena forma física. Pistas pavimentadas en su mayoría. El punto de inicio de la Ruta es accesible en transporte público.</descripcion>
      <personas_adecuadas>Personas en buena forma física y que sepan montar en bicicleta</personas_adecuadas>
      <inicio>
          <lugar>Siep Riep</lugar>
          <direccion>9V34+5PR, 7 Makara St, Krong Siem Reap, Camboya</direccion>
          <coordenadas>
            <longitud>13.3527778</longitud>
            <latitud>103.85666666666665</latitud>
            <altitud>15.03</altitud>
          </coordenadas>
      </inicio>
      <referencias>
        <referencia>
          <titulo>Templo Angkor Wat</titulo>
          <bibliografia>https://es.wikipedia.org/wiki/Angkor_Wat</bibliografia>
        </referencia>
        <referencia>
          <titulo>Ciudad de Siem Riep</titulo>
          <bibliografia>https://es.wikipedia.org/wiki/Siem_Riep_(ciudad)</bibliografia>
        </referencia>
        <referencia>
          <titulo>Información sobre el Templo de Bayón</titulo>
          <bibliografia>https://es.wikipedia.org/wiki/Bay%C3%B3n</bibliografia>
        </referencia>
      </referencias>
      <recomendacion>6</recomendacion>
      <!--Primer hito-->
      <hitos>
        <hito>
          <nombre>Baksei Chamkrong</nombre>
          <descripcion>Pequeño templo hinduista ubicado en el complejo de Angkor. Está dedicado a Shiva y solía albergar una imagen de él. Este templo se puede ver en la parte izquierda, cuando se entra a Angkor Thom por la puerta sur.</descripcion>
          <coordenadas>
            <longitud>13.4252778</longitud>
            <latitud>103.85833333333333</latitud>
            <altitud>22</altitud>
          </coordenadas>
          <distancia unidades="km">12</distancia>
          <galeria_fotos>
            <foto>Baksei.jpg</foto>
            <foto>BakseiInterior.jpg</foto>
          </galeria_fotos>
        </hito>
        <!--Segundo hito-->
        <hito>
          <nombre>Templo de Bayón</nombre>
          <descripcion>El templo de Bayón es un complejo de culto en el centro de la antigua ciudad de Angkor Thom, que se encuentra en la región de Angkor, Camboya. El complejo de Angkor, incluido Angkor Thom, fue declarado Patrimonio de la Humanidad por la Unesco en 1992.</descripcion>
          <coordenadas>
            <longitud>13.4411111</longitud>
            <latitud>103.85972222222222</latitud>
            <altitud>40</altitud>
          </coordenadas>
          <distancia unidades="km">2.1</distancia>
          <galeria_fotos>
            <foto>Bayon.jpg</foto>
          </galeria_fotos>
        </hito>
        <!--Tercer hito-->
        <hito>
          <nombre>Khamosh Gate (gate of the dead)</nombre>
          <descripcion>La "Gran Ciudad" de Jayavarman VII (el significado de Angkor Thom) abarcaba un área de unos 9 kilómetros cuadrados y sólo se podía entrar a través de cinco puertas. En el norte, sur y oeste, solo una puerta proporcionaba acceso, mientras que el lado este tenía una puerta que conducía al palacio real (la llamada Puerta de la Victoria) y otra puerta al sur ahora conocida como la Puerta de los Muertos.</descripcion>
          <coordenadas>
            <longitud>13.4413889</longitud>
            <latitud>103.87333333333332</latitud>
            <altitud>30</altitud>
          </coordenadas>
          <distancia unidades="km">7.2</distancia>
          <galeria_fotos>
            <foto>GateOfTheDead.jpg</foto>
          </galeria_fotos>
        </hito>
      </hitos>
  </ruta>


  <!-- TERCERA RUTA -->
  <ruta>
    <nombre>Recorrido en coche por la Costa Sur de Camboya</nombre>
    <tipo>Turismo</tipo>
    <medio>Coche</medio>
    <fecha_inicio>2019-07-15</fecha_inicio>
    <hora_inicio>09:00:00</hora_inicio>
    <duracion>P2D</duracion>
    <agencia>Sin agencia</agencia>
    <descripcion>Explora la impresionante costa sur de Camboya en un emocionante recorrido en coche. Descubre playas, parques nacionales y encantadores pueblos costeros. Salida desde la ciudad de Sihanoukville.</descripcion>
    <personas_adecuadas>Cualquier persona es adecuada para esta ruta</personas_adecuadas>
    <inicio>
      <lugar>Sihanoukville</lugar>
      <direccion>Sihanoukville, Camboya</direccion>
      <coordenadas>
        <longitud>10.6191667</longitud>
        <latitud>103.49333333333334</latitud>
        <altitud>31</altitud>
      </coordenadas>
    </inicio>
    <referencias>
      <referencia>
        <titulo>Ciudad de Kep</titulo>
        <bibliografia>https://www.mochileandoporasia.com/mochileando-por-camboya/kep/</bibliografia>
      </referencia>
      <referencia>
        <titulo>¿Qué ver en Kampot?</titulo>
        <bibliografia>https://www.descubrir.com/que-ver-en-kampot-un-oasis-al-sur-camboya/</bibliografia>
      </referencia>
      <referencia>
        <titulo>Cosas a saber sobre "Otres Beach"</titulo>
        <bibliografia>https://www.tripadvisor.es/Attraction_Review-g325573-d1451692-Reviews-Otres_Beach-Sihanoukville_Sihanoukville_Province.html</bibliografia>
      </referencia>
    </referencias>
    <recomendacion>10</recomendacion>
    <!-- Primer hito -->
    <hitos>
      <hito>
        <nombre>Playa Otres</nombre>
        <descripcion>Una hermosa playa de arena blanca en Sihanoukville, ideal para nadar y relajarse bajo el sol.</descripcion>
        <coordenadas>
          <longitud>10.5716667</longitud>
          <latitud>103.55138888888888</latitud>
          <altitud>3</altitud>
        </coordenadas>
        <distancia unidades="km">9.7</distancia>
        <galeria_fotos>
          <foto>otres.jpg</foto>
        </galeria_fotos>
      </hito>
      <!-- Segundo hito -->
      <hito>
